server:
  port: 80
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:data;DB_CLOSE_ON_EXIT=FALSE
    username: sa
security:
  user:
    name: admin
    password: zero
logging:
  level:
    org:
      springframework: INFO

---
spring:
  profiles: debug
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  file: C:\log\blog.log
server:
  port: 8080

---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:/root/data/data;DB_CLOSE_ON_EXIT=FALSE
    username: sa
security:
  user:
    name: admin
    password: secret-password
logging:
  level:
    org:
      springframework: INFO
  file: /root/logs/blog.log
