INSERT INTO configuration
(id, author,    upload_path,         creation_date) VALUES
( 1, 'Anna', '/root/uploads/', '2015-01-01 12:00:00');

INSERT INTO post
(id,          title,           content, author,         creation_date, active) VALUES
( 1, 'test title 1',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a aliquet nibh. Integer sed sem pretium, commodo sapien sit amet, viverra felis. Nullam eget lectus nisl. In hac habitasse platea dictumst. Sed pretium consectetur mi eget sodales. Morbi egestas, risus a lacinia varius, ligula odio fermentum nibh, at vestibulum velit arcu id leo. Nulla blandit est eros, id sagittis magna tincidunt at. Aenean scelerisque magna nec blandit convallis. Maecenas congue laoreet mattis. Phasellus vel dictum nulla. Quisque at ipsum pretium, auctor augue non, varius enim. Curabitur elementum arcu in leo convallis, nec ullamcorper lorem placerat. Fusce quam tortor, ullamcorper id justo vel, malesuada dapibus ante. Mauris imperdiet dui lectus, id gravida odio bibendum a. Suspendisse sollicitudin consectetur elit. Fusce aliquet nisi hendrerit elit gravida, eget pretium turpis ultricies. Fusce a auctor mauris, non tristique turpis. Nunc odio quam, aliquam ac ipsum eget, varius aliquet augue. Vestibulum sodales consectetur justo, quis finibus velit facilisis et. Fusce hendrerit dui ac tempus rutrum. Quisque dolor sapien, porta vel facilisis non, vestibulum sed tortor. Vestibulum ut auctor augue. Quisque pretium ex libero, eu dictum mauris sollicitudin non. Phasellus at cursus libero. In eget nisi odio. Vestibulum commodo sit amet odio id suscipit. Aenean libero nibh, auctor vel maximus quis, pretium aliquam nunc. Etiam nec augue sagittis, sollicitudin mi in, blandit dolor. Nullam lacus dolor, consectetur sit amet sapien vel, sodales ullamcorper neque. Duis lobortis gravida egestas. Nullam congue accumsan risus, tempus mattis neque sagittis quis. Donec eu nunc hendrerit, mattis dui eget, fermentum arcu. Phasellus vehicula nulla quis nulla pretium vestibulum. Aliquam id dui ut massa laoreet pretium egestas id eros. Suspendisse et molestie lectus. Nullam hendrerit efficitur luctus. Nullam a tortor elementum, euismod diam vel, lobortis massa. Cras vitae mauris mattis urna ornare semper et ut nunc. Proin in sapien mattis, iaculis ex vel, tempus velit. Nulla dictum nibh vehicula sapien egestas, ultricies fringilla massa accumsan. Maecenas justo turpis, volutpat ut nibh vel, finibus finibus risus. Proin sit amet dui nunc. Vestibulum in condimentum nulla. Fusce tempor, eros sit amet malesuada gravida, turpis mi laoreet metus, eget ullamcorper turpis libero rhoncus ligula. Praesent eu lacus eget metus commodo gravida. Vivamus erat arcu, lacinia a nisi quis, placerat dictum ipsum. Nam ultricies feugiat consectetur. Donec elementum lacinia lacinia. Donec ligula diam, ultricies ut ultrices a, consequat tempor dolor. Maecenas quis fringilla erat, a aliquet lectus. Etiam a auctor ligula, quis elementum purus.', 'Anna', '2015-01-01 12:00:00',   true),
( 2, 'test title 2',  'test content 2', 'Anna', '2015-01-01 11:00:00',   true),
( 3, 'test title 3',  'test content 3', 'Anna', '2015-01-01 10:00:00',   true);

INSERT INTO photo
(id, post_id,       path) VALUES
( 1,       1, 'test1.jpg'),
( 2,       1, 'test2.jpg');