drop table post if exists;

create table post (
        id bigint generated by default as identity,
        active boolean not null,
        author varchar(255) not null,
        content blob not null,
        creation_date timestamp not null,
        title varchar(255) not null,
        primary key (id)
    );
